-- Create USERS table (no references to ADDRESSES)
CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    PAYMENT_INFO TEXT,
    DEFAULT_PAYMENT VARCHAR(500),
    PHONE_NUMBER VARCHAR(50)
);

-- Create ADDRESSES table with foreign key to USERS and default flag
CREATE TABLE ADDRESSES (
    ADDRESS_ID UUID PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    STREET_LINE2 VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    ZIP_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    USER_ID UUID NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create SHOPD_ITEMS table
CREATE TABLE SHOPD_ITEMS (
    ITEM_ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DOUBLE PRECISION NOT NULL,
    IMAGE_URL VARCHAR(500),
    CATEGORY VARCHAR(100) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    QUANTITY INTEGER NOT NULL,
    USER_ID UUID NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);