CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL
);

CREATE TABLE SHOPD_ITEMS (
    ITEM_ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DOUBLE PRECISION NOT NULL,
    IMAGE_URL VARCHAR(500),
    CATEGORY VARCHAR(100) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    QUANTITY INTEGER NOT NULL,
    USER_ID UUID NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);