CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL
);